version: "3.8"

services:
  be:
    build: ./be
    ports:
      - "8000:8000"
    volumes:
      - ./be:/app
    working_dir: /app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  fe:
    build: ./fe
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
